spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pcd-db?characterEncoding=utf8
    username: postgres
    password: GP_SA524
  profiles:
    include: oauth, jwt
  jpa:
    database: postgresql
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true


springdoc:
  packages-to-scan=: com.springboot.domain